[".zgen"]
type = "git-repo"
url = "https://github.com/tarjoilija/zgen.git"

[".config/alacritty/themes/one_light.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/one_light.toml"

[".config/alacritty/themes/tokyo_night.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/tokyo_night.toml"

[".config/alacritty/themes/tokyo_night_storm.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/tokyo_night_storm.toml"

[".config/alacritty/themes/rose_pine_dawn.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/rose_pine_dawn.toml"

[".config/alacritty/themes/rose_pine_moon.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/rose_pine_moon.toml"

[".config/alacritty/themes/rose_pine.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/rose_pine.toml"

[".config/alacritty/themes/dracula.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/dracula.toml"
