[".zgen"]
type = "git-repo"
url = "https://github.com/tarjoilija/zgen.git"

[".config/alacritty/themes/one_light.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/refs/heads/master/themes/one_light.toml"

[".config/alacritty/themes/tokyo-night.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/tokyo-night.toml"

[".config/alacritty/themes/tokyo-night-storm.toml"]
type = "file"
url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/tokyo-night-storm.toml"

[".config/alacritty/themes/rose-pine-dawn.toml"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/alacritty/main/dist/rose-pine-dawn.toml"

[".config/alacritty/themes/rose-pine-moon.toml"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/alacritty/main/dist/rose-pine-moon.toml"

[".config/alacritty/themes/rose-pine.toml"]
type = "file"
url = "https://raw.githubusercontent.com/rose-pine/alacritty/main/dist/rose-pine.toml"

[".config/alacritty/themes/dracula.toml"]
type = "file"
url = "https://raw.githubusercontent.com/dracula/alacritty/master/dracula.toml"
