# Atom One Light Theme for Alacritty in TOML format

[colors.primary]
foreground = '#383a42'
background = '#fafafa'
dim_foreground = '#a0a1a7'
bright_foreground = '#383a42'

[colors.cursor]
text = '#fafafa'
cursor = '#383a42'

[colors.vi_mode_cursor]
text = '#fafafa'
cursor = '#383a42'

[colors.search.matches]
foreground = '#383a42'
background = '#e5e5e5'

[colors.search.focused_match]
foreground = '#fafafa'
background = '#e45649'

[colors.hints.start]
foreground = '#383a42'
background = '#f0f0f0'

[colors.hints.end]
foreground = '#a0a1a7'
background = '#f0f0f0'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#383a42'
background = '#f0f0f0'

[colors.selection]
text = '#383a42'
background = '#e5e5e5'

[colors.normal]
black = '#383a42'
red = '#e45649'
green = '#50a14f'
yellow = '#c18401'
blue = '#0184bc'
magenta = '#a626a4'
cyan = '#0997b3'
white = '#a0a1a7'

[colors.bright]
black = '#696c77'
red = '#e45649'
green = '#50a14f'
yellow = '#c18401'
blue = '#0184bc'
magenta = '#a626a4'
cyan = '#0997b3'
white = '#fafafa'

[colors.dim]
black = '#696c77'
red = '#e45649'
green = '#50a14f'
yellow = '#c18401'
blue = '#0184bc'
magenta = '#a626a4'
cyan = '#0997b3'
white = '#fafafa'
