import = [
  "~/.config/alacritty/themes/atom-one-light.toml",
  "~/.config/alacritty/fonts.toml",
]

[shell]
program = "/opt/homebrew/bin/fish"
# args = ["--login"]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
decorations_theme_variant = "None"
dynamic_title = true
startup_mode = "Maximized"
