[general]
import = [
  "~/.config/alacritty/themes/tokyo-night-storm.toml",
  "~/.config/alacritty/fonts.toml",
]

# [terminal.shell]
# For a smooth transition, we can use the login switch to load legacy files like
# .profile during fish startup. Not required!
# args = ["--login"]
# program = "/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "screen-256color"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
decorations_theme_variant = "None"
dynamic_title = true
startup_mode = "Maximized"
opacity = 0.98
title = "Terminal"
